#-------------------------------------------------------------
# Copyright (c) 1997 IFA Informatik
# All Rights Reserved
#
# $Id$
#-------------------------------------------------------------

all:

include ../../../Makefile.master
	
clean:		clean2

release:	release2

zip:
	zip images.zip *.jpg *.gif Makefile

# DO NOT DELETE THIS LINE -- make depend depends on it.
